import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill
import telebot
import os

# 1. CONFIGURAÇÕES DO TELEGRAM
TOKEN = "8615638167:AAHlJZAkrDHXFf-nrklJXGjo9SuOtnO0_lI"
CHAT_ID = "5091720896"  # ID do seu chat capturado pelo sistema
bot = telebot.TeleBot(TOKEN)

def executar_pipeline_automatizada():
    print("🚀 [PASSO 1] Iniciando o robô de relatórios do Excel...")
    
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = "Relatório de Vendas"
    
    dados_vendas = [
        ["Produto", "Quantidade", "Preço Unitário (R$)", "Total Faturado (R$)"],
        ["Notebook Intel i7", 5, 4500.00, "=B2*C2"],
        ["Monitor UltraWide 29", 12, 1300.00, "=B3*C3"],
        ["Teclado Mecânico RGB", 25, 350.00, "=B4*C4"],
        ["Mouse Gamer Wireless", 40, 220.00, "=B5*C5"],
        ["Cadeira Ergonômica", 8, 1100.00, "=B6*C6"]
    ]
    
    for linha in dados_vendas:
        sheet.append(linha)
        
    # Estilização do cabeçalho
    cor_azul_escuro = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
    fonte_branca_negrito = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    alinhamento_centralizado = Alignment(horizontal="center", vertical="center")
    
    for celula in sheet[1]:
        celula.fill = cor_azul_escuro
        celula.font = fonte_branca_negrito
        celula.alignment = alinhamento_centralizado
        
        # Ajusta automaticamente a largura das colunas
        # Ajusta automaticamente a largura das colunas de forma infalível
    for i, col in enumerate(sheet.columns, start=1):
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = openpyxl.utils.get_column_letter(i)
        sheet.column_dimensions[col_letter].width = max(max_len + 4, 12)

    nome_arquivo = "relatorio_vendas_automatico.xlsx"
    workbook.save(nome_arquivo)
    print(f"✨ Planilha criada e salva localmente como: [{nome_arquivo}]")
    
    # -------------------------------------------------------------
    print("\n📲 [PASSO 2] Iniciando disparo de alerta para o Telegram...")
    try:
        # Envia a mensagem de texto avisando o dono da empresa
        mensagem_alerta = "📊 **DAILY REPORT AUTOMATION**\n\nHello Ronaldo! Your sales report has been successfully generated by Python and is ready for analysis."
        bot.send_message(CHAT_ID, mensagem_alerta, parse_mode="Markdown")
        print("📨 Mensagem de texto enviada com sucesso!")
        
        # Envia o próprio arquivo do Excel direto para o celular do cliente
        print("📎 Anexando e enviando o arquivo .xlsx...")
        with open(nome_arquivo, "rb") as arquivo_excel:
            bot.send_document(CHAT_ID, arquivo_excel)
        print("🔥 Concluído! Relatório enviado direto para o Telegram!")
        
    except Exception as erro:
        print(f"🚨 Falha ao enviar a notificação no Telegram: {erro}")

if __name__ == "__main__":
    executar_pipeline_automatizada()
